[22;0t]0;IPython: ML_Nuclear_Data/SAVIOReading data into dataframe...
Data read into dataframe!
Transforming Energy to Log10(Energy)...
Converting data to numerical...
Splitting dataset into training and testing...
Normalizing dataset..
Finished.
[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
[0;32m~/ML_Nuclear_Data/SAVIO/XGB_EXFOR.py[0m in [0;36m<module>[0;34m[0m
[1;32m     14[0m [0;34m[0m[0m
[1;32m     15[0m df, x_train, x_test, y_train, y_test, to_scale, scaler = exfor_utils.load_exfor((data_path + "ML_Data/working_xs_v2_unraw.csv"), 
[0;32m---> 16[0;31m     numerical=True, plotting_df=False, give_split=True, norm=True, log_e=log_E)
[0m[1;32m     17[0m [0;34m[0m[0m
[1;32m     18[0m [0;34m[0m[0m

[0;32m~/ML_Nuclear_Data/Utilities/EXFOR_utilities.py[0m in [0;36mload_exfor[0;34m(datapath, numerical, plotting_df, give_split, frac, norm, log_e)[0m
[1;32m     50[0m             [0mx_test[0m[0;34m[[0m[0mto_scale[0m[0;34m][0m [0;34m=[0m [0mscaler[0m[0;34m.[0m[0mtransform[0m[0;34m([0m[0mx_test[0m[0;34m[[0m[0mto_scale[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     51[0m         [0mprint[0m[0;34m([0m[0;34m"Finished."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 52[0;31m         [0;32mreturn[0m [0mdf[0m[0;34m,[0m [0mdf_plotting[0m[0;34m,[0m [0mx_train[0m[0;34m,[0m [0mx_test[0m[0;34m,[0m [0my_train[0m[0;34m,[0m [0my_test[0m[0;34m,[0m [0mto_scale[0m[0;34m,[0m [0mscaler[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     53[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     54[0m         [0;32mif[0m [0mplotting_df[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mUnboundLocalError[0m: local variable 'df_plotting' referenced before assignment
